### ISSUE TITLE
Easy-M3U-Playlist-Editor

### ISSUE THREAD

**Issue by coolrose78** [imrsaleh/Easy-M3U-Playlist-Creator#2]
Any possibility for Easy-M3U-Playlist-Editor with
mpd dash #KODIPROP:inputstream.adaptive.license_type= 
m3u playlist editor
Just an idea only
thank you

**Comment by imrsaleh** [comment]
that value depends on the type of MPD manifest you have.
If your MPD uses Widevine, you can use the value: com.widevine.alpha.
If it uses Microsoft PlayReady, you can use the value: com.microsoft.playready.
If it uses ClearKey, you can use the appropriate ClearKey value.
Please refer to the documentation of your MPD type to ensure the correct usage of the value according to its technical requirements.

If MPD manifest is free and does not require a license, you can leave it empty
